###FUNCTIONS CODE GENERATED BY SUPERVISOR'S TEAM TO PERFORM CLUSTERING### ----------------------------------------------------------

# Makes a mask with stars for GW significance

makeStarMask <- function(df){
  z_mask <- matrix(nrow = nrow(df), ncol = ncol(df))
  for (i in 1:nrow(df)) {
    for (j in 1:ncol(df)) {
      if (2*pnorm(-abs(df[i, j])) < 5.0e-08){
        z_mask[i, j] <- "***"
      }
      else if (2*pnorm(-abs(df[i, j])) < 5.0e-07){
        z_mask[i, j] <- "**"
      }
      else if (2*pnorm(-abs(df[i, j])) < 5.0e-06) {
        z_mask[i, j] <- "*"
      }
    }
  }
  return(z_mask)
}

# Truncates to GW significane (note: Z-table should be unscaled)
truncate <- function(df, z_value){
  for (i in 1:nrow(df)) {
    for (j in 1:ncol(df)) {
      if (2*pnorm(-abs(df[i, j])) < 5.0e-08){
        if (df[i,j] < 0){
          df[i,j] <- -5.45
        } else if (df[i,j] > 0){
          df[i,j] <- 5.45
        }
      } 
    }
  }
  return(df)
}

# Truncates to 3sd
truncate_3sd <- function(df, z_value){
  for (j in 1:ncol(df)) {
    lower_limit <- mean(df[ ,j]) - 3*sd(df[ ,j])
    upper_limit <- mean(df[ ,j]) + 3*sd(df[ ,j])
    for (i in 1:nrow(df)) {
      if (df[i, j] < lower_limit ) {
        df[i,j] <- lower_limit
      } else if (df[i,j] > upper_limit ) {
        df[i,j] <- upper_limit
      }
    }
  }
  return(df)
}

# Truncate to 2sd
truncate_2sd <- function(df, z_value){
  for (j in 1:ncol(df)) {
    lower_limit <- mean(df[ ,j]) - 2*sd(df[ ,j])
    upper_limit <- mean(df[ ,j]) + 2*sd(df[ ,j])
    for (i in 1:nrow(df)) {
      if (df[i, j] < lower_limit ) {
        df[i,j] <- lower_limit
      } else if (df[i,j] > upper_limit ) {
        df[i,j] <- upper_limit
      }
    }
  }
  return(df)
}


clusterCols <- function(df){
  d <- dist(t(df), method ="euclidean", upper=T, diag=T)
  col_clust <- hclust(d, method = "ward.D")
  return(col_clust)
}

